"""Drawing the mechanism: a scene model, a self-contained HTML viewer, figures.

Three pieces, in dependency order:

``scene``
    Turns a converted mechanism plus its simulations into a :class:`ViewerScene`
    -- plain data describing where everything is at every step of the arc. No
    rendering decisions live here, which is what lets the HTML viewer and the
    PyVista viewer show the same thing.
``html``
    Renders a scene into one file with no external dependencies, for looking at
    on a phone at the printer.
``figures``
    The publication and README figures, regenerated by ``cmtool figures``.

``palette`` holds the colours and dash patterns all of them share, so a series
looks the same wherever it appears.

Matplotlib is only imported by ``figures``, so the viewer works without the
``plot`` extra installed.
"""

from cmtool.viz.html import external_references, render_html, write_html
from cmtool.viz.palette import SERIES, strain_colour
from cmtool.viz.scene import ModelFrame, ModelSeries, ViewerScene, build_scene

__all__ = [
    "SERIES",
    "ModelFrame",
    "ModelSeries",
    "ViewerScene",
    "build_scene",
    "external_references",
    "render_html",
    "strain_colour",
    "write_html",
]
